---
pool: sweety

trigger:
  - efficient-webjars

resources:
  repositories:
  - repository: 'AzureReusuableTemplates'
    endpoint: github.com_Madhuri-chinta
    ref: refs/heads/main 
    name: Madhuri-chinta/neelu 
    type: 'github'  

stages:
- stage: Buildstage
  displayName: Build
  jobs:
  - job: MyJob
    displayName: My First Job
    steps:
    - template: ./spring-maven.yaml@AzureReusuableTemplates
      displayName: Build
    