---
pool:  
  name: sweety

trigger:
  - efficient-webjars

steps:
  - task: Maven@3
    inputs:
      mavenPOMFile: 'pom.xml'
      mavenVersionOption: 'Path'
      mavenDirectory: /opt/apache-maven-3.6.3 
      goals: 'package'
      jdkVersionOption: '1.17'
      javaHomeOption: 'Path'
      jdkDirectory: /usr/lib/jvm/java-1.17.0-openjdk-amd64


    

   