---
pool: sweety

trigger:
  - master

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DOCKER' 
    repository: 'madhurichinta/gol'
    command: 'buildAndPush' 
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId)'
      