---
pool: "sweety"

trigger:
  - main

variables:
  name: madhuri
  value: true  

steps:
- task: Npm@1
  inputs:
    command: 'install'
    verbose: $(madhuri)
    publishPackageMetadata: true
    